package httpapi

import (
	"encoding/hex"
	"net/http"

	"github.com/DoMinhHHung/beebox/internal/audit"
)

// correlationForRequest reuses only the canonical 16-byte hex request IDs
// generated by the BeeBox Gateway. Other direct/client-supplied request IDs are
// not trusted as audit correlation and receive a fresh random correlation ID.
// Correlation is observability evidence only and never authorization input.
func correlationForRequest(r *http.Request) (audit.CorrelationID, error) {
	if r != nil {
		values := r.Header.Values(RequestIDHeader)
		if len(values) == 1 && len(values[0]) == 32 {
			decoded, err := hex.DecodeString(values[0])
			if err == nil && len(decoded) == 16 {
				var correlation audit.CorrelationID
				copy(correlation[:], decoded)
				if correlation != (audit.CorrelationID{}) {
					return correlation, nil
				}
			}
		}
	}
	return audit.NewCorrelationID()
}
