package httpapi

const hostedJSV2 = `
(function(){
"use strict";
var csrf=document.querySelector('meta[name="csrf-token"]').content;
var root=document.documentElement;
var state={access:"",pending:"",hostedMFA:false};
var result=document.getElementById("result");
var status=document.getElementById("status");
var continueLink=document.getElementById("continue-link");
var pkInput=document.getElementById("publishable-key");
var accessInput=document.getElementById("access-token");
var reverifyInput=document.getElementById("reverification");
var strings={
 en:{skip:"Skip to content",subtitle:"Hosted authentication",language:"Language",theme:"Theme",connect:"Connect application",connectHelp:"Use the application's BeeBox publishable key. Nothing is stored in browser storage.",primary:"Sign up and sign in",signup:"Email + password sign up",password:"Password",passwordSignin:"Password sign in",submit:"Submit",signin:"Sign in",emailOtp:"Email OTP",emailOtpConfirm:"Confirm email OTP",sendCode:"Send code",code:"Code",confirm:"Confirm",emailLink:"Email sign-in link",returnUrl:"Return URL",sendLink:"Send link",phoneSignup:"Phone sign up",phoneSignupConfirm:"Confirm phone sign up",phoneSignin:"Phone OTP sign in",phoneSigninConfirm:"Confirm phone OTP",phone:"Phone",mfa:"Multi-factor authentication",mfaHelp:"Pending MFA authority is kept only in memory or a Secure HttpOnly hosted cookie.",method:"Method",completeMfa:"Complete MFA",passkeys:"Passkeys",passkeySignin:"Sign in with passkey",passkeyRegister:"Register passkey",listPasskeys:"List passkeys",passkeyId:"Passkey ID",remove:"Remove",social:"Social sign in",socialHelp:"Social authorization uses BeeBox's existing PKCE-bound headless flow and the application's exact redirect allowlist.",provider:"Provider",continueSocial:"Continue",account:"Account and profile",loadProfile:"Load profile",listEmails:"List emails",listPhones:"List phones",updateProfile:"Update profile",displayName:"Display name",givenName:"Given name",familyName:"Family name",save:"Save",addEmail:"Add email",addPhone:"Add phone",add:"Add",identifierType:"Type",identifierId:"Identifier ID",action:"Action",security:"Security factors",totpState:"TOTP state",startTotp:"Start TOTP enrollment",recoveryState:"Recovery-code state",regenerateRecovery:"Regenerate recovery codes",enrollmentId:"Enrollment ID",sessions:"Sessions",listSessions:"List sessions",revokeOthers:"Revoke other sessions",signoutEverywhere:"Sign out everywhere",sessionId:"Session ID",revoke:"Revoke",result:"Result",continue:"Continue",accessToken:"Access token",reverification:"Reverification grant"},
 vi:{skip:"Bỏ qua đến nội dung",subtitle:"Xác thực được lưu trữ",language:"Ngôn ngữ",theme:"Giao diện",connect:"Kết nối ứng dụng",connectHelp:"Dùng publishable key của ứng dụng BeeBox. Không lưu token vào bộ nhớ trình duyệt.",primary:"Đăng ký và đăng nhập",signup:"Đăng ký email + mật khẩu",password:"Mật khẩu",passwordSignin:"Đăng nhập bằng mật khẩu",submit:"Gửi",signin:"Đăng nhập",emailOtp:"OTP email",emailOtpConfirm:"Xác nhận OTP email",sendCode:"Gửi mã",code:"Mã",confirm:"Xác nhận",emailLink:"Liên kết đăng nhập email",returnUrl:"URL quay lại",sendLink:"Gửi liên kết",phoneSignup:"Đăng ký bằng số điện thoại",phoneSignupConfirm:"Xác nhận đăng ký điện thoại",phoneSignin:"Đăng nhập OTP điện thoại",phoneSigninConfirm:"Xác nhận OTP điện thoại",phone:"Số điện thoại",mfa:"Xác thực đa yếu tố",mfaHelp:"Quyền MFA tạm thời chỉ ở bộ nhớ hoặc cookie Secure HttpOnly.",method:"Phương thức",completeMfa:"Hoàn tất MFA",passkeys:"Passkey",passkeySignin:"Đăng nhập bằng passkey",passkeyRegister:"Đăng ký passkey",listPasskeys:"Danh sách passkey",passkeyId:"ID passkey",remove:"Xóa",social:"Đăng nhập mạng xã hội",socialHelp:"Luồng social dùng PKCE headless hiện có và redirect allowlist chính xác của ứng dụng.",provider:"Nhà cung cấp",continueSocial:"Tiếp tục",account:"Tài khoản và hồ sơ",loadProfile:"Tải hồ sơ",listEmails:"Danh sách email",listPhones:"Danh sách điện thoại",updateProfile:"Cập nhật hồ sơ",displayName:"Tên hiển thị",givenName:"Tên",familyName:"Họ",save:"Lưu",addEmail:"Thêm email",addPhone:"Thêm điện thoại",add:"Thêm",identifierType:"Loại",identifierId:"ID định danh",action:"Hành động",security:"Yếu tố bảo mật",totpState:"Trạng thái TOTP",startTotp:"Bắt đầu TOTP",recoveryState:"Trạng thái mã khôi phục",regenerateRecovery:"Tạo lại mã khôi phục",enrollmentId:"ID đăng ký",sessions:"Phiên đăng nhập",listSessions:"Danh sách phiên",revokeOthers:"Thu hồi phiên khác",signoutEverywhere:"Đăng xuất mọi nơi",sessionId:"ID phiên",revoke:"Thu hồi",result:"Kết quả",continue:"Tiếp tục",accessToken:"Access token",reverification:"Reverification grant"}
};
function locale(){return root.lang==="vi"?"vi":"en"}
function translate(){var table=strings[locale()];document.querySelectorAll("[data-i18n]").forEach(function(el){var v=table[el.dataset.i18n];if(v)el.textContent=v});document.querySelectorAll("[data-i18n-label]").forEach(function(el){var v=table[el.dataset.i18nLabel];if(v&&el.firstChild)el.firstChild.textContent=v})}
function show(data,ok){status.textContent=ok?(locale()==="vi"?"Thành công":"Success"):(locale()==="vi"?"Không thể hoàn tất yêu cầu":"Request failed");result.textContent=JSON.stringify(data,null,2);continueLink.classList.add("hidden");if(data&&data.completion_url){continueLink.href=data.completion_url;continueLink.classList.remove("hidden")}}
function headers(extra){var h={"Content-Type":"application/json","X-BeeBox-CSRF":csrf};var pk=pkInput.value.trim();if(pk)h["X-BeeBox-Publishable-Key"]=pk;var access=state.access||accessInput.value.trim();if(access)h.Authorization="Bearer "+access;var rev=reverifyInput.value.trim();if(rev)h["X-BeeBox-Reverification"]=rev;if(extra)Object.keys(extra).forEach(function(k){h[k]=extra[k]});return h}
async function api(path,method,body,extra){var options={method:method||"GET",headers:headers(extra),credentials:"same-origin"};if(options.method!=="GET"&&options.method!=="HEAD")options.body=JSON.stringify(body||{});var response=await fetch("/auth/api"+path,options);var data={};try{data=await response.json()}catch(_){data={status:response.status}};if(data.access_token){state.access=data.access_token;accessInput.value=data.access_token}if(data.pending_mfa_token){state.pending=data.pending_mfa_token}show(data,response.ok);return {response:response,data:data}}
function formBody(form){var out={};new FormData(form).forEach(function(v,k){if(v!=="")out[k]=v});return out}
document.querySelectorAll(".api-form").forEach(function(form){form.addEventListener("submit",async function(e){e.preventDefault();var extra={};if(form.dataset.idempotency==="true")extra["Idempotency-Key"]=crypto.randomUUID();try{await api(form.dataset.path,form.dataset.method,formBody(form),extra)}catch(_){show({error:"network_error"},false)}})})
document.querySelectorAll(".simple-call").forEach(function(button){button.addEventListener("click",async function(){try{await api(button.dataset.path,button.dataset.method,{},null)}catch(_){show({error:"network_error"},false)}})})
document.getElementById("mfa-form").addEventListener("submit",async function(e){e.preventDefault();var code=document.getElementById("mfa-code").value;var method=document.getElementById("mfa-method").value;try{if(state.hostedMFA){var special=method==="recovery_code"?"/mfa/recovery":"/mfa/totp";var r=await api(special,"POST",{code:code},null);if(r.response.ok&&r.data.access_token)state.hostedMFA=false}else{var path=method==="recovery_code"?"/v1/mfa/recovery-codes/complete":"/v1/mfa/totp/complete";await api(path,"POST",{pending_mfa_token:state.pending,code:code},null)}}catch(_){show({error:"network_error"},false)}})
document.getElementById("identifier-action-form").addEventListener("submit",async function(e){e.preventDefault();var type=document.getElementById("identifier-type").value;var id=document.getElementById("identifier-id").value.trim();var action=document.getElementById("identifier-action").value;var code=document.getElementById("identifier-code").value.trim();var path="/v1/identifiers/"+type+"/"+encodeURIComponent(id);var method="POST",body={};if(action==="verify"){path+="/verification";if(code){path+="/confirm";body.code=code}}else if(action==="primary"){path+="/primary"}else{method="DELETE"}await api(path,method,body,null)})
document.getElementById("revoke-session-form").addEventListener("submit",async function(e){e.preventDefault();var id=document.getElementById("revoke-session-id").value.trim();await api("/v1/sessions/"+encodeURIComponent(id)+"/revoke","POST",{},null)})
function b64url(buf){return btoa(String.fromCharCode.apply(null,new Uint8Array(buf))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
document.getElementById("social-form").addEventListener("submit",async function(e){e.preventDefault();var body={provider:document.getElementById("social-provider").value,completion_url:document.getElementById("social-return").value};try{var r=await api("/social/start","POST",body,null);if(r.response.ok&&r.data.authorization_url)location.assign(r.data.authorization_url)}catch(_){show({error:"network_error"},false)}})
function decodeB64url(v){var s=v.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";var bin=atob(s),out=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out.buffer}
function normalizePublicKey(options){if(options.challenge)options.challenge=decodeB64url(options.challenge);if(options.user&&options.user.id)options.user.id=decodeB64url(options.user.id);if(options.allowCredentials)options.allowCredentials.forEach(function(c){c.id=decodeB64url(c.id)});if(options.excludeCredentials)options.excludeCredentials.forEach(function(c){c.id=decodeB64url(c.id)});return options}
function credentialJSON(cred){var response={clientDataJSON:b64url(cred.response.clientDataJSON)};if(cred.response.attestationObject)response.attestationObject=b64url(cred.response.attestationObject);if(cred.response.authenticatorData)response.authenticatorData=b64url(cred.response.authenticatorData);if(cred.response.signature)response.signature=b64url(cred.response.signature);if(cred.response.userHandle)response.userHandle=b64url(cred.response.userHandle);return {id:cred.id,rawId:b64url(cred.rawId),type:cred.type,response:response,clientExtensionResults:cred.getClientExtensionResults()}}
document.getElementById("passkey-signin").addEventListener("click",async function(){try{var begin=await api("/v1/passkeys/authentication/attempts","POST",{},null);if(!begin.response.ok)return;var opts=begin.data.public_key||begin.data.options||begin.data;var cred=await navigator.credentials.get({publicKey:normalizePublicKey(opts)});await api("/v1/passkeys/authentication/complete","POST",{attempt_id:begin.data.attempt_id,credential:credentialJSON(cred)},null)}catch(_){show({error:"passkey_failed"},false)}})
document.getElementById("passkey-register").addEventListener("click",async function(){try{var begin=await api("/v1/passkeys/registration/attempts","POST",{},null);if(!begin.response.ok)return;var opts=begin.data.public_key||begin.data.options||begin.data;var cred=await navigator.credentials.create({publicKey:normalizePublicKey(opts)});await api("/v1/passkeys/registration/complete","POST",{attempt_id:begin.data.attempt_id,credential:credentialJSON(cred)},null)}catch(_){show({error:"passkey_failed"},false)}})
document.getElementById("passkey-remove-form").addEventListener("submit",async function(e){e.preventDefault();var id=document.getElementById("passkey-remove-id").value.trim();await api("/v1/passkeys/"+encodeURIComponent(id),"DELETE",{},null)})
document.getElementById("language").value=locale();document.getElementById("language").addEventListener("change",function(e){root.lang=e.target.value==="vi"?"vi":"en";translate()});document.getElementById("theme").value=root.dataset.theme;document.getElementById("theme").addEventListener("change",function(e){var v=e.target.value;root.dataset.theme=(v==="light"||v==="dark")?v:"system"});translate();
async function consumeEmailLink(){if(location.pathname!=="/auth/email-link")return;var params=new URLSearchParams(location.search);var challenge=params.get("challenge")||"";var pk=params.get("pk")||"";var fragment=new URLSearchParams(location.hash.slice(1));var secret=fragment.get("secret")||"";history.replaceState(null,"",location.pathname+location.search);pkInput.value=pk;if(!challenge||!pk||!secret){show({error:"invalid_email_link"},false);return}try{var response=await fetch("/auth/api/email-link/confirm",{method:"POST",credentials:"same-origin",headers:headers(null),body:JSON.stringify({challenge_id:challenge,secret:secret})});var data={};try{data=await response.json()}catch(_){data={}};if(data.access_token){state.access=data.access_token;accessInput.value=data.access_token}if(data.status==="mfa_required")state.hostedMFA=true;show(data,response.ok)}catch(_){show({error:"network_error"},false)}}
async function consumeSocialCallback(){if(location.pathname!=="/auth/social/callback")return;var params=new URLSearchParams(location.search);var code=params.get("beebox_code")||"";var failed=params.get("beebox_error")||"";history.replaceState(null,"",location.pathname);if(failed||!code){show({error:"social_auth_failed"},false);return}try{var response=await fetch("/auth/api/social/exchange",{method:"POST",credentials:"same-origin",headers:headers(null),body:JSON.stringify({code:code})});var data={};try{data=await response.json()}catch(_){data={}};if(data.access_token){state.access=data.access_token;accessInput.value=data.access_token}if(data.status==="mfa_required")state.hostedMFA=true;show(data,response.ok)}catch(_){show({error:"network_error"},false)}}
consumeEmailLink();consumeSocialCallback();
})();
`
